### ISSUE TITLE
Docker Todos

### ISSUE THREAD

**Issue by tomit4** [tomit4/vite_via_nginx#1]
Currently, we're learning docker networking to implement this application in production. This is my first time doing this, so here are some notes regarding how to proceed. Once all are checked, we can resolve this issue:

**TODO**:

- [x] Spin up a basic postgresql image/container on a custom network that cannot reach
      out to the host network, but can be seen by our fastify server. Get it to
      populate/interact via our fastify server before continuing on.
- [x] Same thing with the redis image/container.
- [x] Spin up a basic nodejs image/container for our fastify server. This is our
      point of failure. It can talk to our postgresql container, our redis container,
      and exposes its endpoints for our vuejs/frontend server to see. Again, get
      the vuejs/frontend still running on our host to talk to it first (package
      the vuejs app for production and serve it on our local HOST via
      nginx first before continuing on). Postgresql docker container, Redis
      container, and fastify/nodejs container should all be on the same docker
      network, but only the fastifyjs/nodejs can talk to the vuejs/frontend
      (which should be on their own network???).
- [x] UPDATE: Got this working, but had to expose a backend port. No worries, we
      will just have to change .env vars and code on front end to accommodate for
      directly routing to ip address/port.
- [x] Additionally, we'll need to rewrite our multiple docker-compose.yml files
      into one so that we can easily spin them up and down using the
      docker-compose command. See [this helpful link](https://www.thegeekstuff.com/2016/04/docker-compose-up-stop-rm/) for more info. Additionally, it appears that on reboot of the machine, the docker containers don't start up in the same order, assigning random ip addresses and throwing our configurations off. we'll need to use the links or depends_on keywords in the .yml file to ensure they start up in order, see [this stack overflow post](https://stackoverflow.com/questions/38731998/do-docker-container-ips-change-on-restart).
- [x] Spin up another nodejs server that encampsulates our vuejs/frontend
      application that is served inside the container via nginx, and exposes a port to
      the host machine nginx server. It should be able to query the fastify
      server as well.

**NOTES**

Ok, learned a lot. Our docker instances should all spin up accordingly. We have
created a dockerify script we can use like so to spin up or down our
backend/frontend accordingly (from the root of our project directory).

```bash
# Spin up
doas ./dockerify -u
```

```bash
# Spin down
doas ./dockerify -d
```

Now, because https is not enabled, and fastify attempts to set a secure cookie,
the browser rejects this because it is not sent over https, and instead is
sent over the local http via docker. There are two solutions for local
development of this. Both involve using openssl to generate a self signed
certificate.

One solution is where we set the .pem cert directly in [fastify's configuration directly](https://github.com/fastify/fastify/issues/355). As the author goes on though, setting ssl certs and having node process them directly is computationally expensive and is better handled from NGINX.

Thusly:

- [x] Set up a dockerized nginx reverse proxy that utilizes a self signed ssl certificate in its configuration file as well as proxies out the fastify/nodejs server instead of running it directly from the docker container.
